package com.puneeth450.offlinetoolbox.app.navigation

object Routes {
    const val HOME = "home"
    const val FAVORITES = "favorites"
    const val UPDATES = "updates"
    const val SETTINGS = "settings"
    const val SETTINGS_LAYOUT = "settings_layout"
    const val SETTINGS_CATEGORY_COLORS = "settings_category_colors"
    const val ANALOG_CLOCK = "analog_clock"
    const val DIGITAL_CLOCK = "digital_clock"
    const val TIME_ZONE_CONVERTER = "time_zone_converter"
    const val CALENDAR = "calendar"
    const val TIMER = "timer"
    const val POMODORO = "pomodoro"
    const val STOPWATCH_TIMER = "stopwatch_timer"
    const val BREATHING = "breathing"
    const val TALLY = "tally"
    const val EMI = "emi"
    const val SPLIT_BILL = "split_bill"
    const val DISCOUNT = "discount"
    const val RULE72 = "rule72"
    const val JSON = "json"
    const val URL_CODEC = "url_codec"
    const val HASH = "hash"
    const val LOREM = "lorem"
    const val COLOR = "color"
    const val FLASHLIGHT = "flashlight"
    const val DEVICE_INFO = "device_info"
    const val UNIT_CONVERTER = "unit_converter"
}
